var palabrasIngles = [
    
    'Abstract ',
    'Algorithm ',
    'API (Application Programming Interface) ',
    'Application ',
    'Array ',
    'Argument ',
    'Binary ',
    'Boolean ',
    'Breakpoint ',
    'Bug ',
    'Byte ',
    'Cache ',
    'Callback ',
    'Class ',
    'Client ',
    'Code ',
    'Compiler ',
    'Constant ',
    'Constructor ',
    'Coroutine ',
    'CSS (Cascading Style Sheets) ',
    'Debug ',
    'Declaration ',
    'Decompile ',
    'Dependency ',
    'Deprecated ',
    'Directive ',
    'DOM (Document Object Model) ',
    'Element ',
    'Encapsulation ',
    'Enum ',
    'Error ',
    'Event ',
    'Exception ',
    'Execute ',
    'Expression ',
    'File ',
    'Firewall ',
    'Float ',
    'Framework ',
    'Function ',
    'Garbage Collection ',
    'Global ',
    'GUI (Graphical User Interface) ',
    'Hash ',
    'HTML (Hypertext Markup Language) ',
    'IDE (Integrated Development Environment) ',
    'If-else ',
    'Implementation ',
    'Inheritance ',
    'Input ',
    'Instance ',
    'Integer ',
    'Interface ',
    'Interpreter ',
    'IP Address ',
    'JavaScript ',
    'JIT (Just-In-Time) ',
    'Keyword ',
    'Library ',
    'Linker ',
    'Local ',
    'Loop ',
    'Machine Code ',
    'Memory ',
    'Method ',
    'Middleware ',
    'Module ',
    'MVC (Model-View-Controller) ',
    'Namespace ',
    'Native ',
    'Null ',
    'Object ',
    'Operand ',
    'Operator ',
    'Output ',
    'Overload ',
    'Package ',
    'Paradigm ',
    'Parameter ',
    'Parse ',
    'Patch ',
    'Path ',
    'Pointer ',
    'Polymorphism ',
    'Port ',
    'Preprocessor ',
    'Primitive ',
    'Private ',
    'Procedure ',
    'Program ',
    'Protocol ',
    'Public ',
    'Query ',
    'Recursion ',
    'Reference ',
    'Regex (Regular Expression) ',
    'Release ',
    'Remote ',
    'Repository ',
    'Request ',
    'Response ',
    'Return ',
    'Runtime ',
    'Scope ',
    'SDK (Software Development Kit) ',
    'Security ',
    'Semaphore ',
    'Server ',
    'Session ',
    'SQL (Structured Query Language) ',
    'Stack ',
    'Statement ',
    'Static ',
    'String ',
    'Struct ',
    'Subroutine ',
    'Switch ',
    'Syntax ',
    'System ',
    'TCP/IP (Transmission Control Protocol/Internet Protocol) ',
    'Template ',
    'Test ',
    'Thread ',
    'Token ',
    'Transaction ',
    'Try-catch ',
    'Type ',
    'UI (User Interface) ',
    'Unicode ',
    'URL (Uniform Resource Locator) ',
    'Variable ',
    'Version ',
    'Virtual ',
    'Void ',
    'VPN (Virtual Private Network) ',
    'Web ',
    'XML (Extensible Markup Language) ',
    'Abstraction ',
    'Access ',
    'Adapter ',
    'Annotation ',
    'API ',
    'Applet ',
    'Architecture ',
    'Argument ',
    'Arithmetic ',
    'Assertion ',
    'Assembly ',
    'Atomic ',
    'Authentication ',
    'Batching ',
    'Benchmark ',
    'Big Data ',
    'Binding ',
    'BIOS (Basic Input/Output System) ',
    'Bit ',
    'Block ',
    'Branch ',
    'Buffer ',
    'Build ',
    'Bytecode ',
    'Cache ',
    'Call ',
    'Callback ',
    'Call Stack ',
    'Canonicalization ',
    'Case-sensitive ',
    'CD-ROM (Compact Disc Read-Only Memory) ',
    'Cell ',
    'CGI (Common Gateway Interface) ',
    'Character ',
    'Class ',
    'Classpath ',
    'Client ',
    'Client-server ',
    'Closure ',
    'Cloud Computing ',
    'Cluster ',
    'CMS (Content Management System) ',
    'Code ',
    'Codec ',
    'Coding ',
    'Command ',
    'Command-line ',
    'Comments ',
    'Compiler ',
    'Component ',
    'Computation ',
    'Concatenation ',
    'Concurrency ',
    'Configuration ',
    'Constructor ',
    'Container ',
    'Content ',
    'Context ',
    'Control ',
    'Cookie ',
    'Core ',
    'CRUD (Create, Read, Update, Delete) ',
    'Cryptography ',
    'CSS (Cascading Style Sheets) ',
    'Cursor - Cursor ',
    'Customization ',
    'Cybersecurity ',
    'Data ',
    'Database ',
    'Debugging ',
    'Declaration ',
    'Decryption ',
    'Default ',
    'Dependency ',
    'Deployment ',
    'Design ',
    'Destructor ',
    'Development ',
    'DHCP (Dynamic Host Configuration Protocol) ',
    'Diagram ',
    'Digital Signature ',
    'Directory ',
    'Dispatch ',
    'Distribution ',
    'DNS (Domain Name System) ',
    'Documentation ',
    'Domain ',
    'DOS (Disk Operating System) ',
    'Dot ',
    'Download ',
    'Driver ',
    'Dynamic ',
    'Eclipse ',
    'Edge ',
    'Efficiency ',
    'Element ',
    'Encapsulation ',
    'Encoding ',
    'Endpoint ',
    'Environment ',
    'Error ',
    'Escape Character ',
    'Event ',
    'Exception ',
    'Execution ',
    'Expression ',
    'Extension ',
    'Failover ',
    'File ',
    'Filesystem ',
    'Firewall ',
    'Flag ',
    'Flash ',
    'Flowchart ',
    'Folder ',
    'Font ',
    'Framework ',
    'Front-end ',
    'FTP (File Transfer Protocol) ',
    'Function ',
    'Gateway ',
    'Generator ',
    'Generic ',
    'Git ',
    'Global ',
    'Goto ',
    'GUI (Graphical User Interface) ',
    'Hack ',
    'Handler ',
    'Hard Disk ',
    'Hash ',
    'Header ',
    'Heap ',
    'Hierarchy ',
    'Hook ',
    'Hosting ',
    'HTML (Hypertext Markup Language) ',
    'HTTP (Hypertext Transfer Protocol) ',
    'HTTPS (Hypertext Transfer Protocol Secure) ',
    'Hyperlink ',
    'IDE (Integrated Development Environment) ',
    'If-else ',
    'IIFE (Immediately Invoked Function Expression) ',
    'Image ',
    'Immutable ',
    'Index ',
    'Inheritance ',
    'Injection ',
    'Inline ',
    'Input ',
    'Instance ',
    'Integer ',
    'Interface ',
    'Interpreter ',
    'Intranet ',
    'IP Address ',
    'ISP (Internet Service Provider) ',
    'Iteration ',
    'Java - ',
    'JavaScript ',
    'JIT (Just-In-Time) ',
    'JSON (JavaScript Object Notation) ',
    
    ];
    
    var palabrasEspanol = [
        'Abstracto - ',
        'Algoritmo - ',
        'Interfaz de Programación de Aplicaciones - ',
        'Aplicación - ',
        'Arreglo - ',
        'Argumento - ',
        'Binario - ',
        'Booleano - ',
        'Punto de Interrupción - ',
        'Error - ',
        'Byte - ',
        'Caché - ',
        'Llamada de Retorno - ',
        'Clase - ',
        'Cliente - ',
        'Código - ',
        'Compilador - ',
        'Constante - ',
        'Constructor - ',
        'Corrutina - ',
        'Hojas de Estilo en Cascada - ',
        'Depurar - ',
        'Declaración - ',
        'Descompilar - ',
        'Dependencia - ',
        'Obsoleto - ',
        'Directiva - ',
        'Modelo de Objetos de Documento - ',
        'Elemento - ',
        'Encapsulación - ',
        'Enumeración - ',
        'Error - ',
        'Evento - ',
        'Excepción - ',
        'Ejecutar - ',
        'Expresión - ',
        'Archivo - ',
        'Cortafuegos - ',
        'Flotante - ',
        'Marco de Trabajo - ',
        'Función - ',
        'Recolección de Basura - /',
        'Global - ',
        'Interfaz Gráfica de Usuario - ',
        'Hash - ',
        'Lenguaje de Marcado de Hipertexto - ',
        'Entorno de Desarrollo Integrado - ',
        'Si-sino - /',
        'Implementación - ',
        'Herencia - ',
        'Entrada - ',
        'Instancia - ',
        'Entero - ',
        'Interfaz - ',
        'Intérprete - ',
        'Dirección IP - /aɪ ',
        'JavaScript - ',
        'Justo a Tiempo - ',
        'Palabra Clave - ',
        'Biblioteca - ',
        'Enlazador - ',
        'Local - ',
        'Bucle - ',
        'Código Máquina - /',
        'Memoria - ',
        'Método - ',
        'Middleware - ',
        'Módulo - ',
        'Modelo-Vista-Controlador - ',
        'Espacio de Nombres - ',
        'Nativo - ',
        'Nulo - ',
        'Objeto - ',
        'Operando - ',
        'Operador - ',
        'Salida - ',
        'Sobrecarga - ',
        'Paquete - ',
        'Paradigma - ',
        'Parámetro - ',
        'Analizar - ',
        'Parche - ',
        'Ruta - ',
        'Puntero - ',
        'Polimorfismo - ',
        'Puerto - ',
        'Preprocesador - ',
        'Primitivo - ',
        'Privado - ',
        'Procedimiento - ',
        'Programa - ',
        'Protocolo - ',
        'Público - ',
        'Consulta - ',
        'Recursión - ',
        'Referencia - ',
        'Expresión Regular - ',
        'Liberación - ',
        'Remoto - ',
        'Repositorio - ',
        'Petición - ',
        'Respuesta - ',
        'Devolver - ',
        'Tiempo de Ejecución - ',
        'Ámbito - ',
        'Kit de Desarrollo de Software - ',
        'Seguridad - ',
        'Semáforo - ',
        'Servidor - ',
        'Sesión - ',
        'Lenguaje de Consulta Estructurado - /ɛs ',
        'Pila - ',
        'Sentencia - ',
        'Estático - ',
        'Cadena - ',
        'Estructura - ',
        'Subrutina - ',
        'Cambiar - ',
        'Sintaxis - ',
        'Sistema - ',
        'Protocolo de Control de Transmisión/Protocolo de Internet - /tiː siː piː ',
        'Plantilla - ',
        'Prueba - ',
        'Hilo - ',
        'Token - ',
        'Transacción - ',
        'Intentar-capturar - /',
        'Tipo - ',
        'Interfaz de Usuario - ',
        'Unicode - ',
        'Localizador de Recursos Uniforme - ',
        'Variable - ',
        'Versión - ',
        'Virtual - ',
        'Vacío - ',
        'Red Privada Virtual - /viː ',
        'Web - ',
        'Lenguaje de Marcado Extensible - ',
        'Abstracción - ',
        'Acceso - ',
        'Adaptador - ',
        'Anotación - ',
        'Interfaz de Programación de Aplicaciones - /ˌeɪ ',
        'Applet - ',
        'Arquitectura - ',
        'Argumento - ',
        'Aritmética - ',
        'Aserción - ',
        'Ensamblaje - ',
        'Atómico - ',
        'Autenticación - ',
        'Agrupamiento - ',
        'Referencia - ',
        'Grandes Datos - /',
        'Vinculación - ',
        'Sistema Básico de Entrada/Salida - ',
        'Bit - ',
        'Bloque - ',
        'Rama - ',
        'Búfer - ',
        'Compilar - ',
        'Código de Byte - ',
        'Caché - ',
        'Llamada - ',
        'Llamada de Retorno - ',
        'Pila de Llamadas - /',
        'Canonicación - ',
        'Sensible a Mayúsculas y Minúsculas - /',
        'Disco Compacto de Memoria de Solo Lectura - /siː ',
        'Celda - ',
        'Interfaz de Pasarela Común - ',
        'Carácter - ',
        'Clase - ',
        'Ruta de Clase - ',
        'Cliente - ',
        'Cliente-Servidor - /',
        'Clausura - ',
        'Computación en la Nube - /',
        'Grupo - ',
        'Sistema de Gestión de Contenidos - ',
        'Código - ',
        'Codificador-Decodificador - ',
        'Codificación - ',
        'Comando - ',
        'Línea de Comando - /',
        'Comentarios - ',
        'Compilador - ',
        'Componente - ',
        'Computación - ',
        'Concatenación - ',
        'Concurrencia - ',
        'Configuración - ',
        'Constructor - ',
        'Contenedor - ',
        'Contenido - ',
        'Contexto - ',
        'Control - ',
        'Cookie - ',
        'Núcleo - ',
        'Crear, Leer, Actualizar, Eliminar - ',
        'Criptografía - ',
        'Hojas de Estilo en Cascada - ',
        
        'Personalización - ',
        'Ciberseguridad - ',
        'Datos - ',
        'Base de Datos - ',
        'Depuración - ',
        'Declaración - ',
        'Descifrado - ',
        'Predeterminado - ',
        'Dependencia - ',
        'Despliegue - ',
        'Diseño - ',
        'Destructor - ',
        'Desarrollo - ',
        'Protocolo de Configuración Dinámica de Host - /diː aɪ siː ',
        'Diagrama - ',
        'Firma Digital - /',
        'Directorio - ',
        'Despacho - ',
        'Distribución - ',
        'Sistema de Nombres de Dominio - ',
        'Documentación - ',
        'Dominio - ',
        'Sistema Operativo de Disco - ',
        'Punto - ',
        'Descargar - ',
        'Controlador - ',
        'Dinámico - ',
        'Eclipse - ',
        'Borde - ',
        'Eficiencia - ',
        'Elemento - ',
        'Encapsulación - ',
        'Codificación - ',
        'Punto Final - ',
        'Entorno - ',
        'Error - ',
        'Carácter de Escape - /',
        'Evento - ',
        'Excepción - ',
        'Ejecución - ',
        'Expresión - ',
        'Extensión - ',
        'Conmutación por Error - ',
        'Archivo - ',
        'Sistema de Archivos - ',
        'Cortafuegos - ',
        'Bandera - ',
        'Flash - ',
        'Diagrama de Flujo - ',
        'Carpeta - ',
        'Fuente - ',
        'Marco de Trabajo - ',
        'Frontal - /',
        'Protocolo de Transferencia de Archivos - /ɛf ',
        'Función - ',
        'Pasarela - ',
        'Generador - ',
        'Genérico - ',
        'Git - ',
        'Global - ',
        'Ir a - ',
        'Interfaz Gráfica de Usuario - ',
        'Hackear - ',
        'Controlador - ',
        'Disco Duro - /',
        'Hash - ',
        'Encabezado - ',
        'Montón - ',
        'Jerarquía - ',
        'Gancho - ',
        'Alojamiento - ',
        'Lenguaje de Marcado de Hipertexto - ',
        'Protocolo de Transferencia de Hipertexto - ',
        'Protocolo de Transferencia de Hipertexto Seguro - ',
        'Hipervínculo - ',
        'Entorno de Desarrollo Integrado - ',
        'Si-sino - /',
        'Expresión de Función Invocada Inmediatamente - ',
        'Imagen - ',
        'Inmutable - ',
        'Índice - ',
        'Herencia - ',
        'Inyección - ',
        'En Línea - ',
        'Entrada - ',
        'Instancia - ',
        'Entero - ',
        'Interfaz - ',
        'Intérprete - ',
        'Intranet - ',
        'Dirección IP - /aɪ ',
        'Proveedor de Servicios de Internet - ',
        'Iteración - ',
       'ava - ',
        'JavaScript - ',
        'Justo a Tiempo - ',
        'Notación de Objetos de JavaScript - ',
     
    ];
    
    var pronunciaciones = [
        '/ˈæbstrækt/',
    '/ˈælɡəˌrɪðəm/',
    '/ˌeɪ piː ˈaɪ/',
    '/ˌæplɪˈkeɪʃən/',
    '/əˈreɪ/',
    '/ˈɑːɡjʊmənt/',
    '/ˈbaɪnəri/',
    '/ˈbuːliən/',
    '/ˈbreɪkˌpɔɪnt/',
    '/bʌɡ/',
    '/baɪt/',
    '/kæʃ/',
    '/ˈkɔːlbæk/',
    '/klæs/',
    '/ˈklaɪənt/',
    '/koʊd/',
    '/kəmˈpaɪlər/',
    '/ˈkɒnstənt/',
    '/kənˈstrʌktər/',
    '/ˈkɔːˌraʊtiːn/',
    '/siːɛsɛs/',
    '/dɪˈbʌɡ/',
    '/ˌdɛkləˈreɪʃən/',
    '/diːˈkɒmpaɪl/',
    '/dɪˈpɛndənsi/',
    '/dɪˈprɛkeɪtɪd/',
    '/dəˈrɛktɪv/',
    '/diˌɒm/',
    '/ˈɛlɪmənt/',
    '/ɪnˌkæpsjʊˈleɪʃən/',
    '/ˈinjʊm/',
    '/ˈɛrər/',
    '/ɪˈvɛnt/',
    '/ɪkˈsɛpʃən/',
    '/ˈɛksɪˌkjut/',
    '/ɪkˈsprɛʃən/',
    '/faɪl/',
    '/ˈfaɪərˌwɔːl/',
    '/floʊt/',
    '/ˈfreɪmˌwɜːrk/',
    '/ˈfʌŋkʃən/',
    'ˈɡɑrbɪdʒ kəˈlɛkʃən/',
    '/ˈɡloʊbəl/',
    '/ˈɡwi/',
    '/hæʃ/',
    '/eɪʧtiːɛmɛl/',
    '/aɪdiːiː/',
    'ɪf ɛls/',
    '/ˌɪmplɪmɛnˈteɪʃən/',
    '/ɪnˈhɛrɪtəns/',
    '/ˈɪnpʊt/',
    '/ˈɪnstəns/',
    '/ˈɪntɪdʒər/',
    '/ˈɪntərˌfeɪs/',
    '/ɪnˈtɜːrprɪtər/',
    'piː ˈædrəs/',
    '/ˈʤævəˌskrɪpt/',
    '/ʤɪt/',
    '/ˈkiːwɜːrd/',
    '/ˈlaɪbrəri/',
    '/ˈlɪŋkər/',
    '/ˈloʊkəl/',
    '/luːp/',
    'məˈʃiːn koʊd/',
    '/ˈmɛməri/',
    '/ˈmɛθəd/',
    '/ˈmɪdəlˌwɛr/',
    '/ˈmɒdjuːl/',
    '/ɛmviːsiː/',
    '/ˈneɪmspɛɪs/',
    '/ˈneɪtɪv/',
    '/nʌl/',
    '/ˈɒbdʒɪkt/',
    '/ˈɒpəˌrænd/',
    '/ˈɒpəˌreɪtər/',
    '/ˈaʊtpʊt/',
    '/ˌoʊvərˈloʊd/',
    '/ˈpækɪʤ/',
    '/ˈpærədaɪm/',
    '/pəˈræmɪtər/',
    '/pɑːrs/',
    '/pætʃ/',
    '/pæθ/',
    '/ˈpɔɪntər/',
    '/ˌpɑːliˈmɔrfɪzəm/',
    '/pɔːrt/',
    '/ˌpriːˈprɒsɛsər/',
    '/ˈprɪmətɪv/',
    '/ˈpraɪvɪt/',
    '/prəˈsiːdʒər/',
    '/ˈproʊɡræm/',
    '/ˈproʊtəˌkɒl/',
    '/ˈpʌblɪk/',
    '/ˈkwɪri/',
    '/rɪˈkɜrʒən/',
    '/ˈrɛfərəns/',
    '/ˈrɛɡɛks/',
    '/rɪˈlis/',
    '/rɪˈmoʊt/',
    '/rɪˈpɒzɪtɔːri/',
    '/rɪˈkwɛst/',
    '/rɪˈspɒns/',
    '/rɪˈtɜːrn/',
    '/ˈrʌntaɪm/',
    '/skoʊp/',
    '/ɛsdiːkeɪ/',
    '/sɪˈkjʊrɪti/',
    '/ˈsɛməfɔːr/',
    '/ˈsɜːrvər/',
    '/ˈsɛʃən/',
    'kjuː ˈɛl/',
    '/stæk/',
    '/ˈsteɪtmənt/',
    '/ˈstætɪk/',
    '/strɪŋ/',
    '/strʌkt/',
    '/ˈsʌbruːˌtiːn/',
    '/swɪʧ/',
    '/ˈsɪntæks/',
    '/ˈsɪstəm/',
    'aɪ piː/',
    '/ˈtɛmplɪt/',
    '/tɛst/',
    '/θrɛd/',
    '/ˈtoʊkən/',
    '/trænˈzækʃən/',
    'traɪ kæʧ/',
    '/taɪp/',
    '/juːaɪ/',
    '/ˈjuːnɪkoʊd/',
    '/juːɑːrˈɛl/',
    '/ˈvɛriəbl/',
    '/ˈvɜːrʒən/',
    '/ˈvɜːrtʃuəl/',
    '/vɔɪd/',
    'piː ɛn/',
    '/wɛb/',
    '/ɛksmeɪɛl/',
    '/əˈstrækʃən/',
    '/ˈæksɛs/',
    '/əˈdæptər/',
    '/ˌænəˈteɪʃən/',
    'piː ˈeɪ/',
    '/ˈæplɪt/',
    '/ˈɑːrkɪtɛkʃər/',
    '/ˈɑːɡjʊmənt/',
    '/əˈrɪθmətɪk/',
    '/əˈsɜːrʃən/',
    '/əˈsɛmbli/',
    '/əˈtɒmɪk/',
    '/ɔːˌθɛntɪˈkeɪʃən/',
    '/ˈbætʃɪŋ/',
    '/ˈbɛntʃmɑːrk/',
    'bɪɡ ˈdeɪtə/',
    '/ˈbaɪndɪŋ/',
    '/ˈbaɪɒs/',
    '/bɪt/',
    '/blɒk/',
    '/bræntʃ/',
    '/ˈbʌfər/',
    '/bɪld/',
    '/ˈbaɪtkoʊd/',
    '/kæʃ/',
    '/kɔːl/',
    '/ˈkɔːlbæk/',
    'kɔːl stæk/',
    '/kəˌnɒnɪkəlaɪˈzeɪʃən/',
    'keɪs ˈsɛnsɪtɪv/',
    'diː rɒm/',
    '/sɛl/',
    '/siːʤiːaɪ/',
    '/ˈkærɪktər/',
    '/klæs/',
    '/ˈklɑːspæθ/',
    '/ˈklaɪənt/',
    'ˈklaɪənt ˈsɜːrvər/',
    '/ˈkloʊʒər/',
    'klaʊd kəmˈpjuːtɪŋ/',
    '/ˈklʌstər/',
    '/siːɛmɛs/',
    '/koʊd/',
    '/ˈkoʊdɛk/',
    '/ˈkoʊdɪŋ/',
    '/kəˈmænd/',
    'kəˈmænd laɪn/',
    '/ˈkɒmɛnts/',
    '/kəmˈpaɪlər/',
    '/kəmˈpoʊnənt/',
    '/ˌkɒmpjuːˈteɪʃən/',
    '/kənˌkætəˈneɪʃən/',
    '/kənˈkʌrənsi/',
    '/kənˌfɪɡjʊˈreɪʃən/',
    '/kənˈstrʌktər/',
    '/kənˈteɪnər/',
    '/ˈkɒntɛnt/',
    '/ˈkɒntɛkst/',
    '/kənˈtroʊl/',
    '/ˈkʊki/',
    '/kɔːr/',
    '/krʌd/',
    '/krɪpˈtɒɡrəfi/',
    '/siːɛsɛs/',
    '/ˈkɜːrsər/',
    '/ˌkʌstəmaɪˈzeɪʃən/',
    '/ˌsaɪbərˈsɪkjʊrɪti/',
    '/ˈdeɪtə/',
    '/ˈdeɪtəbeɪs/',
    '/ˈdɛbʌɡɪŋ/',
    '/ˌdɛkləˈreɪʃən/',
    '/dɪˈkrɪpʃən/',
    '/dɪˈfɔːlt/',
    '/dɪˈpɛndənsi/',
    '/dɪˈplɔɪmənt/',
    '/dɪˈzaɪn/',
    '/dɪˈstrʌktər/',
    '/dɪˈvɛləpmənt/',
    'eɪʧ piː/',
    '/ˈdaɪəˌɡræm/',
    'ˈdɪdʒɪtəl ˈsɪɡnətʃər/',
    '/dɪˈrɛktəri/',
    '/dɪˈspætʃ/',
    '/ˌdɪstrɪˈbjuːʃən/',
    '/diːɛnɛs/',
    '/ˌdɒkjʊmɛnˈteɪʃən/',
    '/doʊˈmeɪn/',
    '/dɒs/',
    '/dɒt/',
    '/ˈdaʊnˌloʊd/',
    '/ˈdraɪvər/',
    '/daɪˈnæmɪk/',
    '/ɪˈklɪps/',
    '/ɛdʒ/',
    '/ɪˈfɪʃənsi/',
    '/ˈɛlɪmənt/',
    '/ɪnˌkæpsjʊˈleɪʃən/',
    '/ɪnˈkoʊdɪŋ/',
    '/ˈɛndˌpɔɪnt/',
    '/ɪnˈvaɪrənmənt/',
    '/ˈɛrər/',
    'ɪsˈkeɪp ˈkærɪktər/',
    '/ɪˈvɛnt/',
    '/ɪkˈsɛpʃən/',
    '/ˌɛksɪˈkjuːʃən/',
    '/ɪkˈsprɛʃən/',
    '/ɪkˈstɛnʃən/',
    '/ˈfeɪloʊvər/',
    '/faɪl/',
    '/ˈfaɪlˌsɪstəm/',
    '/ˈfaɪərˌwɔːl/',
    '/flæɡ/',
    '/flæʃ/',
    '/ˈfloʊˌʧɑrt/',
    '/ˈfoʊldər/',
    '/fɒnt/',
    '/ˈfreɪmˌwɜːrk/',
    'frʌnt ɛnd/',
    'tiː piː/',
    '/ˈfʌŋkʃən/',
    '/ˈɡeɪtweɪ/',
    '/ˈʤɛnəˌreɪtər/',
    '/ʤəˈnɛrɪk/',
    '/ɡɪt/',
    '/ˈɡloʊbəl/',
    '/ˈɡoʊˌtuː/',
    '/ˈɡwi/',
    '/hæk/',
    '/ˈhændlər/',
    'hɑrd dɪsk/',
    '/hæʃ/',
    '/ˈhɛdər/',
    '/hip/',
    '/ˈhaɪəˌrɑːrki/',
    '/hʊk/',
    '/ˈhoʊstɪŋ/',
    '/eɪʧtiːɛmɛl/',
    '/eɪʧtiːtiːpiː/',
    '/eɪʧtiːtiːpiːɛs/',
    '/ˈhaɪpərˌlɪŋk/',
    '/aɪdiːaɪiː/',
    'ɪf ɛls/',
    '/aɪfaɪfaɪˈiː/',
    '/ˈɪmɪdʒ/',
    '/ɪˈmjuːtəbl/',
    '/ˈɪndɛks/',
    '/ɪnˈhɛrɪtəns/',
    '/ɪnˈʤɛkʃən/',
    '/ˈɪnˌlaɪn/',
    '/ˈɪnpʊt/',
    '/ˈɪnstəns/',
    '/ˈɪntɪdʒər/',
    '/ˈɪntərˌfeɪs/',
    '/ɪnˈtɜːrprɪtər/',
    '/ˈɪntrəˌnɛt/',
    'piː ˈædrəs/',
    '/aɪɛspɪ/',
    '/ˌɪtəˈreɪʃən/',
    '/ˈʤɑːvə/',
    '/ˈʤævəˌskrɪpt/',
    '/ʤɪt/',
    '/ˈʤeɪsɒn/',
    
    ];

    export { palabrasEspanol };
    export{ palabrasIngles}
    export { pronunciaciones };
