var palabrasIngles = [
    'Abstract ',
    'Algorithm ',
    'API (Application Programming Interface) ',
    'Application ',
    'Array ',
    'Argument ',
    'Binary ',
    'Boolean ',
    'Breakpoint ',
    'Bug ',
    'Byte ',
    'Cache ',
    'Callback ',
    'Class ',
    'Client ',
    'Code ',
    'Compiler ',
    'Constant ',
    'Constructor ',
    'Coroutine ',
    'CSS (Cascading Style Sheets) ',
    'Debug ',
    'Declaration ',
    'Decompile ',
    'Dependency ',
    'Deprecated ',
    'Directive ',
    'DOM (Document Object Model) ',
    'Element ',
    'Encapsulation ',
    'Enum ',
    'Error ',
    'Event ',
    'Exception ',
    'Execute ',
    'Expression ',
    'File ',
    'Firewall ',
    'Float ',
    'Framework ',
    'Function ',
    'Garbage Collection ',
    'Global ',
    'GUI (Graphical User Interface) ',
    'Hash ',
    'HTML (Hypertext Markup Language) ',
    'IDE (Integrated Development Environment) ',
    'If-else ',
    'Implementation ',
    'Inheritance ',
    'Input ',
    'Instance ',
    'Integer ',
    'Interface ',
    'Interpreter ',
    'IP Address ',
    'JavaScript ',
    'JIT (Just-In-Time) ',
    'Keyword ',
    'Library ',
    'Linker ',
    'Local ',
    'Loop ',
    'Machine Code ',
    'Memory ',
    'Method ',
    'Middleware ',
    'Module ',
    'MVC (Model-View-Controller) ',
    'Namespace ',
    'Native ',
    'Null ',
    'Object ',
    'Operand ',
    'Operator ',
    'Output ',
    'Overload ',
    'Package ',
    'Paradigm ',
    'Parameter ',
    'Parse ',
    'Patch ',
    'Path ',
    'Pointer ',
    'Polymorphism ',
    'Port ',
    'Preprocessor ',
    'Primitive ',
    'Private ',
    'Procedure ',
    'Program ',
    'Protocol ',
    'Public ',
    'Query ',
    'Recursion ',
    'Reference ',
    'Regex (Regular Expression) ',
    'Release ',
    'Remote ',
    'Repository ',
    'Request ',
    'Response ',
    'Return ',
    'Runtime ',
    'Scope ',
    'SDK (Software Development Kit) ',
    'Security ',
    'Semaphore ',
    'Server ',
    'Session ',
    'SQL (Structured Query Language) ',
    'Stack ',
    'Statement ',
    'Static ',
    'String ',
    'Struct ',
    'Subroutine ',
    'Switch ',
    'Syntax ',
    'System ',
    'TCP/IP (Transmission Control Protocol/Internet Protocol) ',
    'Template ',
    'Test ',
    'Thread ',
    'Token ',
    'Transaction ',
    'Try-catch ',
    'Type ',
    'UI (User Interface) ',
    'Unicode ',
    'URL (Uniform Resource Locator) ',
    'Variable ',
    'Version ',
    'Virtual ',
    'Void ',
    'VPN (Virtual Private Network) ',
    'Web ',
    'XML (Extensible Markup Language) ',
    'Abstraction ',
    'Access ',
    'Adapter ',
    'Annotation ',
    'API ',
    'Applet ',
    'Architecture ',
    'Argument ',
    'Arithmetic ',
    'Assertion ',
    'Assembly ',
    'Atomic ',
    'Authentication ',
    'Batching ',
    'Benchmark ',
    'Big Data ',
    'Binding ',
    'BIOS (Basic Input/Output System) ',
    'Bit ',
    'Block ',
    'Branch ',
    'Buffer ',
    'Build ',
    'Bytecode ',
    'Cache ',
    'Call ',
    'Callback ',
    'Call Stack ',
    'Canonicalization ',
    'Case-sensitive ',
    'CD-ROM (Compact Disc Read-Only Memory) ',
    'Cell ',
    'CGI (Common Gateway Interface) ',
    'Character ',
    'Class ',
    'Classpath ',
    'Client ',
    'Client-server ',
    'Closure ',
    'Cloud Computing ',
    'Cluster ',
    'CMS (Content Management System) ',
    'Code ',
    'Codec ',
    'Coding ',
    'Command ',
    'Command-line ',
    'Comments ',
    'Compiler ',
    'Component ',
    'Computation ',
    'Concatenation ',
    'Concurrency ',
    'Configuration ',
    'Constructor ',
    'Container ',
    'Content ',
    'Context ',
    'Control ',
    'Cookie ',
    'Core ',
    'CRUD (Create, Read, Update, Delete) ',
    'Cryptography ',
    'CSS (Cascading Style Sheets) ',
    'Cursor - Cursor ',
    'Customization ',
    'Cybersecurity ',
    'Data ',
    'Database ',
    'Debugging ',
    'Declaration ',
    'Decryption ',
    'Default ',
    'Dependency ',
    'Deployment ',
    'Design ',
    'Destructor ',
    'Development ',
    'DHCP (Dynamic Host Configuration Protocol) ',
    'Diagram ',
    'Digital Signature ',
    'Directory ',
    'Dispatch ',
    'Distribution ',
    'DNS (Domain Name System) ',
    'Documentation ',
    'Domain ',
    'DOS (Disk Operating System) ',
    'Dot ',
    'Download ',
    'Driver ',
    'Dynamic ',
    'Eclipse ',
    'Edge ',
    'Efficiency ',
    'Element ',
    'Encapsulation ',
    'Encoding ',
    'Endpoint ',
    'Environment ',
    'Error ',
    'Escape Character ',
    'Event ',
    'Exception ',
    'Execution ',
    'Expression ',
    'Extension ',
    'Failover ',
    'File ',
    'Filesystem ',
    'Firewall ',
    'Flag ',
    'Flash ',
    'Flowchart ',
    'Folder ',
    'Font ',
    'Framework ',
    'Front-end ',
    'FTP (File Transfer Protocol) ',
    'Function ',
    'Gateway ',
    'Generator ',
    'Generic ',
    'Git ',
    'Global ',
    'Goto ',
    'GUI (Graphical User Interface) ',
    'Hack ',
    'Handler ',
    'Hard Disk ',
    'Hash ',
    'Header ',
    'Heap ',
    'Hierarchy ',
    'Hook ',
    'Hosting ',
    'HTML (Hypertext Markup Language) ',
    'HTTP (Hypertext Transfer Protocol) ',
    'HTTPS (Hypertext Transfer Protocol Secure) ',
    'Hyperlink ',
    'IDE (Integrated Development Environment) ',
    'If-else ',
    'IIFE (Immediately Invoked Function Expression) ',
    'Image ',
    'Immutable ',
    'Index ',
    'Inheritance ',
    'Injection ',
    'Inline ',
    'Input ',
    'Instance ',
    'Integer ',
    'Interface ',
    'Interpreter ',
    'Intranet ',
    'IP Address ',
    'ISP (Internet Service Provider) ',
    'Iteration ',
    'Java - ',
    'JavaScript ',
    'JIT (Just-In-Time) ',
    'JSON (JavaScript Object Notation) ',
    ];

    var palabrasEspanol = [
    "abstracto",
    "algoritmo",
    "api (application programming interface)",
    "aplicacion",
    "arreglo",
    "argumento",
    "binario",
    "booleano",
    "punto de interrupcion",
    "error",
    "byte",
    "cache",
    "llamada de retorno",
    "clase",
    "cliente",
    "codigo",
    "compilador",
    "constante",
    "constructor",
    "corutina",
    "css (cascading style sheets)",
    "depurar",
    "declaracion",
    "descompilar",
    "dependencia",
    "desaprobado",
    "directiva",
    "dom (document object model)",
    "elemento",
    "encapsulacion",
    "enum",
    "error",
    "evento",
    "excepcion",
    "ejecutar",
    "expresion",
    "archivo",
    "cortafuegos",
    "flotante",
    "framework",
    "funcion",
    "recoleccion de basura",
    "global",
    "gui (graphical user interface)",
    "hash",
    "html (hypertext markup language)",
    "ide (integrated development environment)",
    "if-else",
    "implementacion",
    "herencia",
    "entrada",
    "instancia",
    "entero",
    "interfaz",
    "interprete",
    "direccion ip",
    "javascript",
    "jit (just-in-time)",
    "palabra clave",
    "biblioteca",
    "vinculador",
    "local",
    "bucle",
    "codigo maquina",
    "memoria",
    "metodo",
    "middleware",
    "modulo",
    "mvc (model-view-controller)",
    "espacio de nombres",
    "nativo",
    "nulo",
    "objeto",
    "operando",
    "operador",
    "salida",
    "sobrecarga",
    "paquete",
    "paradigma",
    "parametro",
    "parsear",
    "parche",
    "ruta",
    "puntero",
    "polimorfismo",
    "puerto",
    "preprocesador",
    "primitivo",
    "privado",
    "procedimiento",
    "programa",
    "protocolo",
    "publico",
    "consulta",
    "recursion",
    "referencia",
    "regex (regular expression)",
    "lanzamiento",
    "remoto",
    "repositorio",
    "peticion",
    "respuesta",
    "retorno",
    "tiempo de ejecucion",
    "alcance",
    "sdk (software development kit)",
    "seguridad",
    "semaforo",
    "servidor",
    "sesion",
    "sql (structured query language)",
    "pila",
    "declaracion",
    "estatico",
    "cadena",
    "struct",
    "subrutina",
    "interruptor",
    "sintaxis",
    "sistema",
    "tcp/ip (transmission control protocol/internet protocol)",
    "plantilla",
    "prueba",
    "hilo",
    "token",
    "transaccion",
    "try-catch",
    "tipo",
    "ui (user interface)",
    "unicode",
    "url (uniform resource locator)",
    "variable",
    "version",
    "virtual",
    "vacio",
    "vpn (virtual private network)",
    "web",
    "xml (extensible markup language)",
    "abstraccion",
    "acceso",
    "adaptador",
    "anotacion",
    "api",
    "applet",
    "arquitectura",
    "argumento",
    "aritmetica",
    "afirmacion",
    "ensamblado",
    "atomico",
    "autenticacion",
    "lote",
    "punto de referencia",
    "big data",
    "vinculacion",
    "bios (basic input/output system)",
    "bit",
    "bloque",
    "rama",
    "buffer",
    "construir",
    "bytecode",
    "cache",
    "llamada",
    "llamada de retorno",
    "pila de llamadas",
    "canonicacion",
    "sensible a mayusculas",
    "cd-rom (compact disc read-only memory)",
    "celda",
    "cgi (common gateway interface)",
    "caracter",
    "clase",
    "classpath",
    "cliente",
    "cliente-servidor",
    "closure",
    "computacion en la nube",
    "cluster",
    "cms (content management system)",
    "codigo",
    "codec",
    "codificacion",
    "comando",
    "linea de comandos",
    "comentarios",
    "compilador",
    "componente",
    "computacion",
    "concatenacion",
    "concurrencia",
    "configuracion",
    "constructor",
    "contenedor",
    "contenido",
    "contexto",
    "control",
    "cookie",
    "nucleo",
    "crud (create, read, update, delete)",
    "criptografia",
    "css (cascading style sheets)",
    "cursor",
    "personalizacion",
    "ciberseguridad",
    "datos",
    "base de datos",
    "depuracion",
    "declaracion",
    "desencriptacion",
    "predeterminado",
    "dependencia",
    "despliegue",
    "diseno",
    "destructor",
    "desarrollo",
    "dhcp (dynamic host configuration protocol)",
    "diagrama",
    "firma digital",
    "directorio",
    "despacho",
    "distribucion",
    "dns (domain name system)",
    "documentacion",
    "dominio",
    "dos (disk operating system)",
    "punto",
    "descargar",
    "controlador",
    "dinamico",
    "eclipse",
    "borde",
    "eficiencia",
    "elemento",
    "encapsulacion",
    "codificacion",
    "punto final",
    "entorno",
    "error",
    "caracter de escape",
    "evento",
    "excepcion",
    "ejecucion",
    "expresion",
    "extension",
    "failover",
    "archivo",
    "sistema de archivos",
    "cortafuegos",
    "bandera",
    "flash",
    "diagrama de flujo",
    "carpeta",
    "fuente",
    "framework",
    "front-end",
    "ftp (file transfer protocol)",
    "funcion",
    "puerta de enlace",
    "generador",
    "generico",
    "git",
    "global",
    "ir a",
    "gui (graphical user interface)",
    "hackeo",
    "manejador",
    "disco duro",
    "hash",
    "encabezado",
    "monticulo",
    "jerarquia",
    "gancho",
    "hospedaje",
    "html (hypertext markup language)",
    "http (hypertext transfer protocol)",
    "https (hypertext transfer protocol secure)",
    "hipervinculo",
    "ide (integrated development environment)",
    "if-else",
    "iife (immediately invoked function expression)",
    "imagen",
    "inmutable",
    "indice",
    "herencia",
    "inyeccion",
    "en linea",
    "entrada",
    "instancia",
    "entero",
    "interfaz",
    "interprete",
    "intranet",
    "direccion ip",
    "isp (internet service provider)",
    "iteracion",
    "java",
    "javascript",
    "jit (just-in-time)",
    "json (javascript object notation)"
    ];
    
    var pronunciaciones = [
        '/ˈæbstrækt/',
    '/ˈælɡəˌrɪðəm/',
    '/ˌeɪ piː ˈaɪ/',
    '/ˌæplɪˈkeɪʃən/',
    '/əˈreɪ/',
    '/ˈɑːɡjʊmənt/',
    '/ˈbaɪnəri/',
    '/ˈbuːliən/',
    '/ˈbreɪkˌpɔɪnt/',
    '/bʌɡ/',
    '/baɪt/',
    '/kæʃ/',
    '/ˈkɔːlbæk/',
    '/klæs/',
    '/ˈklaɪənt/',
    '/koʊd/',
    '/kəmˈpaɪlər/',
    '/ˈkɒnstənt/',
    '/kənˈstrʌktər/',
    '/ˈkɔːˌraʊtiːn/',
    '/siːɛsɛs/',
    '/dɪˈbʌɡ/',
    '/ˌdɛkləˈreɪʃən/',
    '/diːˈkɒmpaɪl/',
    '/dɪˈpɛndənsi/',
    '/dɪˈprɛkeɪtɪd/',
    '/dəˈrɛktɪv/',
    '/diˌɒm/',
    '/ˈɛlɪmənt/',
    '/ɪnˌkæpsjʊˈleɪʃən/',
    '/ˈinjʊm/',
    '/ˈɛrər/',
    '/ɪˈvɛnt/',
    '/ɪkˈsɛpʃən/',
    '/ˈɛksɪˌkjut/',
    '/ɪkˈsprɛʃən/',
    '/faɪl/',
    '/ˈfaɪərˌwɔːl/',
    '/floʊt/',
    '/ˈfreɪmˌwɜːrk/',
    '/ˈfʌŋkʃən/',
    'ˈɡɑrbɪdʒ kəˈlɛkʃən/',
    '/ˈɡloʊbəl/',
    '/ˈɡwi/',
    '/hæʃ/',
    '/eɪʧtiːɛmɛl/',
    '/aɪdiːiː/',
    'ɪf ɛls/',
    '/ˌɪmplɪmɛnˈteɪʃən/',
    '/ɪnˈhɛrɪtəns/',
    '/ˈɪnpʊt/',
    '/ˈɪnstəns/',
    '/ˈɪntɪdʒər/',
    '/ˈɪntərˌfeɪs/',
    '/ɪnˈtɜːrprɪtər/',
    'piː ˈædrəs/',
    '/ˈʤævəˌskrɪpt/',
    '/ʤɪt/',
    '/ˈkiːwɜːrd/',
    '/ˈlaɪbrəri/',
    '/ˈlɪŋkər/',
    '/ˈloʊkəl/',
    '/luːp/',
    'məˈʃiːn koʊd/',
    '/ˈmɛməri/',
    '/ˈmɛθəd/',
    '/ˈmɪdəlˌwɛr/',
    '/ˈmɒdjuːl/',
    '/ɛmviːsiː/',
    '/ˈneɪmspɛɪs/',
    '/ˈneɪtɪv/',
    '/nʌl/',
    '/ˈɒbdʒɪkt/',
    '/ˈɒpəˌrænd/',
    '/ˈɒpəˌreɪtər/',
    '/ˈaʊtpʊt/',
    '/ˌoʊvərˈloʊd/',
    '/ˈpækɪʤ/',
    '/ˈpærədaɪm/',
    '/pəˈræmɪtər/',
    '/pɑːrs/',
    '/pætʃ/',
    '/pæθ/',
    '/ˈpɔɪntər/',
    '/ˌpɑːliˈmɔrfɪzəm/',
    '/pɔːrt/',
    '/ˌpriːˈprɒsɛsər/',
    '/ˈprɪmətɪv/',
    '/ˈpraɪvɪt/',
    '/prəˈsiːdʒər/',
    '/ˈproʊɡræm/',
    '/ˈproʊtəˌkɒl/',
    '/ˈpʌblɪk/',
    '/ˈkwɪri/',
    '/rɪˈkɜrʒən/',
    '/ˈrɛfərəns/',
    '/ˈrɛɡɛks/',
    '/rɪˈlis/',
    '/rɪˈmoʊt/',
    '/rɪˈpɒzɪtɔːri/',
    '/rɪˈkwɛst/',
    '/rɪˈspɒns/',
    '/rɪˈtɜːrn/',
    '/ˈrʌntaɪm/',
    '/skoʊp/',
    '/ɛsdiːkeɪ/',
    '/sɪˈkjʊrɪti/',
    '/ˈsɛməfɔːr/',
    '/ˈsɜːrvər/',
    '/ˈsɛʃən/',
    'kjuː ˈɛl/',
    '/stæk/',
    '/ˈsteɪtmənt/',
    '/ˈstætɪk/',
    '/strɪŋ/',
    '/strʌkt/',
    '/ˈsʌbruːˌtiːn/',
    '/swɪʧ/',
    '/ˈsɪntæks/',
    '/ˈsɪstəm/',
    'aɪ piː/',
    '/ˈtɛmplɪt/',
    '/tɛst/',
    '/θrɛd/',
    '/ˈtoʊkən/',
    '/trænˈzækʃən/',
    'traɪ kæʧ/',
    '/taɪp/',
    '/juːaɪ/',
    '/ˈjuːnɪkoʊd/',
    '/juːɑːrˈɛl/',
    '/ˈvɛriəbl/',
    '/ˈvɜːrʒən/',
    '/ˈvɜːrtʃuəl/',
    '/vɔɪd/',
    'piː ɛn/',
    '/wɛb/',
    '/ɛksmeɪɛl/',
    '/əˈstrækʃən/',
    '/ˈæksɛs/',
    '/əˈdæptər/',
    '/ˌænəˈteɪʃən/',
    'piː ˈeɪ/',
    '/ˈæplɪt/',
    '/ˈɑːrkɪtɛkʃər/',
    '/ˈɑːɡjʊmənt/',
    '/əˈrɪθmətɪk/',
    '/əˈsɜːrʃən/',
    '/əˈsɛmbli/',
    '/əˈtɒmɪk/',
    '/ɔːˌθɛntɪˈkeɪʃən/',
    '/ˈbætʃɪŋ/',
    '/ˈbɛntʃmɑːrk/',
    'bɪɡ ˈdeɪtə/',
    '/ˈbaɪndɪŋ/',
    '/ˈbaɪɒs/',
    '/bɪt/',
    '/blɒk/',
    '/bræntʃ/',
    '/ˈbʌfər/',
    '/bɪld/',
    '/ˈbaɪtkoʊd/',
    '/kæʃ/',
    '/kɔːl/',
    '/ˈkɔːlbæk/',
    'kɔːl stæk/',
    '/kəˌnɒnɪkəlaɪˈzeɪʃən/',
    'keɪs ˈsɛnsɪtɪv/',
    'diː rɒm/',
    '/sɛl/',
    '/siːʤiːaɪ/',
    '/ˈkærɪktər/',
    '/klæs/',
    '/ˈklɑːspæθ/',
    '/ˈklaɪənt/',
    'ˈklaɪənt ˈsɜːrvər/',
    '/ˈkloʊʒər/',
    'klaʊd kəmˈpjuːtɪŋ/',
    '/ˈklʌstər/',
    '/siːɛmɛs/',
    '/koʊd/',
    '/ˈkoʊdɛk/',
    '/ˈkoʊdɪŋ/',
    '/kəˈmænd/',
    'kəˈmænd laɪn/',
    '/ˈkɒmɛnts/',
    '/kəmˈpaɪlər/',
    '/kəmˈpoʊnənt/',
    '/ˌkɒmpjuːˈteɪʃən/',
    '/kənˌkætəˈneɪʃən/',
    '/kənˈkʌrənsi/',
    '/kənˌfɪɡjʊˈreɪʃən/',
    '/kənˈstrʌktər/',
    '/kənˈteɪnər/',
    '/ˈkɒntɛnt/',
    '/ˈkɒntɛkst/',
    '/kənˈtroʊl/',
    '/ˈkʊki/',
    '/kɔːr/',
    '/krʌd/',
    '/krɪpˈtɒɡrəfi/',
    '/siːɛsɛs/',
    '/ˈkɜːrsər/',
    '/ˌkʌstəmaɪˈzeɪʃən/',
    '/ˌsaɪbərˈsɪkjʊrɪti/',
    '/ˈdeɪtə/',
    '/ˈdeɪtəbeɪs/',
    '/ˈdɛbʌɡɪŋ/',
    '/ˌdɛkləˈreɪʃən/',
    '/dɪˈkrɪpʃən/',
    '/dɪˈfɔːlt/',
    '/dɪˈpɛndənsi/',
    '/dɪˈplɔɪmənt/',
    '/dɪˈzaɪn/',
    '/dɪˈstrʌktər/',
    '/dɪˈvɛləpmənt/',
    'eɪʧ piː/',
    '/ˈdaɪəˌɡræm/',
    'ˈdɪdʒɪtəl ˈsɪɡnətʃər/',
    '/dɪˈrɛktəri/',
    '/dɪˈspætʃ/',
    '/ˌdɪstrɪˈbjuːʃən/',
    '/diːɛnɛs/',
    '/ˌdɒkjʊmɛnˈteɪʃən/',
    '/doʊˈmeɪn/',
    '/dɒs/',
    '/dɒt/',
    '/ˈdaʊnˌloʊd/',
    '/ˈdraɪvər/',
    '/daɪˈnæmɪk/',
    '/ɪˈklɪps/',
    '/ɛdʒ/',
    '/ɪˈfɪʃənsi/',
    '/ˈɛlɪmənt/',
    '/ɪnˌkæpsjʊˈleɪʃən/',
    '/ɪnˈkoʊdɪŋ/',
    '/ˈɛndˌpɔɪnt/',
    '/ɪnˈvaɪrənmənt/',
    '/ˈɛrər/',
    'ɪsˈkeɪp ˈkærɪktər/',
    '/ɪˈvɛnt/',
    '/ɪkˈsɛpʃən/',
    '/ˌɛksɪˈkjuːʃən/',
    '/ɪkˈsprɛʃən/',
    '/ɪkˈstɛnʃən/',
    '/ˈfeɪloʊvər/',
    '/faɪl/',
    '/ˈfaɪlˌsɪstəm/',
    '/ˈfaɪərˌwɔːl/',
    '/flæɡ/',
    '/flæʃ/',
    '/ˈfloʊˌʧɑrt/',
    '/ˈfoʊldər/',
    '/fɒnt/',
    '/ˈfreɪmˌwɜːrk/',
    'frʌnt ɛnd/',
    'tiː piː/',
    '/ˈfʌŋkʃən/',
    '/ˈɡeɪtweɪ/',
    '/ˈʤɛnəˌreɪtər/',
    '/ʤəˈnɛrɪk/',
    '/ɡɪt/',
    '/ˈɡloʊbəl/',
    '/ˈɡoʊˌtuː/',
    '/ˈɡwi/',
    '/hæk/',
    '/ˈhændlər/',
    'hɑrd dɪsk/',
    '/hæʃ/',
    '/ˈhɛdər/',
    '/hip/',
    '/ˈhaɪəˌrɑːrki/',
    '/hʊk/',
    '/ˈhoʊstɪŋ/',
    '/eɪʧtiːɛmɛl/',
    '/eɪʧtiːtiːpiː/',
    '/eɪʧtiːtiːpiːɛs/',
    '/ˈhaɪpərˌlɪŋk/',
    '/aɪdiːaɪiː/',
    'ɪf ɛls/',
    '/aɪfaɪfaɪˈiː/',
    '/ˈɪmɪdʒ/',
    '/ɪˈmjuːtəbl/',
    '/ˈɪndɛks/',
    '/ɪnˈhɛrɪtəns/',
    '/ɪnˈʤɛkʃən/',
    '/ˈɪnˌlaɪn/',
    '/ˈɪnpʊt/',
    '/ˈɪnstəns/',
    '/ˈɪntɪdʒər/',
    '/ˈɪntərˌfeɪs/',
    '/ɪnˈtɜːrprɪtər/',
    '/ˈɪntrəˌnɛt/',
    'piː ˈædrəs/',
    '/aɪɛspɪ/',
    '/ˌɪtəˈreɪʃən/',
    '/ˈʤɑːvə/',
    '/ˈʤævəˌskrɪpt/',
    '/ʤɪt/',
    '/ˈʤeɪsɒn/',
    
    ];

    export { palabrasEspanol };
    export{ palabrasIngles}
    export { pronunciaciones };
